### ISSUE TITLE
Warlock: Should they be more tough? Is their Hit Points to low?

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#266]
After a discussion in #heroes-handbook on our Discord with Auvreannia, Tseims, and Ivass. 

Should Warlocks have a larger health pool? It is suggested within WoW and through our own Warlock class' *Life Tap* that Warlocks are very constitutive people that don't go down easy.
As we remove their armor proficiency the Warlock class is going to struggle with getting a high Armor Class and will quickly run out of health for its *Life Tap* feature.

It's been suggested to look at increasing their base HP making the Warlock add twice their Constitution modifier to their Warlock class levels. This would greatly increase their HP, allowing them to use their life tap more vigorously and giving them more of a feel "tough" feel.

**Comment by Jihia** [comment]
Others have mentioned that features like *Life Tap* is great because it is immediately punishing and dangerous to use, if they had an increased health pool the penalty to this spell would become minuscule and not have the same feel of being a dangerous feature.

**Comment by Tyloris** [comment]
While I was initially a proponent that warlocks get a d6 hit die since it is the same as other "squishy" non-armored classes like the priest and mage, there's better evidence that the warlock was always intended to be tougher than the other classes in WoW.

In WoW, if you look at the starting attributes for classes of this or that race, you see that they get bonuses based on which class they are, ranging from +0 to +3. Below are the starting bonuses to Stamina, the relevant classes, and the conversion into hit dice.

+0: Druid, Mage, Priest                                      d6
+1: Hunter, Monk, Rogue, Shaman, Warlock     d8
+2: Paladin, Warrior                                           d10

Which would indicate that Warlocks should get d8.
