### ISSUE TITLE
Druid: Does feral being one spec and a full caster remove class identity?

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#429]
We returned Feral to being a full caster like Balance and Restoration. But does this take away from their identity? Feral are supposed to be a subclass that focuses of its shapeshifts, but as full casters the feral feels like a generic caster who can also do some fighting on the side, opposed to being dedicated to the martial side.

Additionally, it has been mentioned that we might have removed too much of the Feral and Guardian feel by clashing them together.

**Comment by Chokka99** [comment]
If I may lend a little more insight into this issue, I have some ideas.

I like to think of spellcasters by percentages;
Full Casters are at most 30% martial, and 70% (if not 100%) magical, with the likes of Bladesinger, War Cleric, and Valor Bard being the most martial of the full casters.

Half Casters are exactly what the name implies, a 50/50 split of magical and martial ability, with Rangers and Paladins filling this role.

Lastly, Third Casters are the inverse of the Full Casters while still retaining magic, being about 70% focused on martial abilities, and 30% magical. An Eldritch Knight is still very much a Fighter, but with a small amount of magic to complement their fighting prowess.


In reference to the Druid, I think it's clear that making Feral a Third Caster is out of the question, as making a class that is fully proficient in magic simultaneously not being able to reach fifth level spells is confusing and possibly poor class design. And speaking flavor-wise, I would imagine that a feral druid would have at least the magical capabilities of a paladin, if not more.

The options left are Full Caster and Half Caster, and I believe this comes down to how you feel the class should play. If you feel that feral druids should be primarily casters that can get some work done in the front-line, make them Full Casters. If you want them as capable fighters who also boast some not-insignificant magic, make them Half Casters. Now, I'm no game designer, but I believe that you cannot stray too far from these "guidelines" (if you can call them that) without causing some balance issues. Making the Feral Druid as good a caster as a Mage or a Shaman while also being comparable to a Warrior or Paladin in a melee makes them dangerously powerful, perhaps more so than any other class that you have designed.

If I had to take a stance on either side of the argument I would have to say, Half Caster. I cannot imagine a feral druid being far less competent in fighting ability than a similarly optimized Warrior or Paladin. Making them otherwise would, in my opinion, mislead potential players who were coming from WoW, where Guardians tank it up with Prot Warriors, and Ferals can compete with Rogues.

(Small tangent, I _really_ dislike the idea of putting a smite on a full caster to facilitate martial ability. It is, in my opinion, lazy, and Wizards have used other means to accomplish this goal in the past. Bladesingers and Swords Bards buffing themselves, and Hexblades using their spellcasting modifiers to attack come to mind.)

In regards to the clashing of Feral and Guardian, I do agree that in doing so, some of the feel of each playstyle was lost. (Not to mention that the early-game Guardian style of play was weakened massively by moving the defensive effects of blood frenzy to an option at level 10. A d8 class with relatively low AC and few ways to mitigate damage will have a hard time taking hits.)
The 2.1 version of Guardian and Feral felt more like pseudo Warriors and Rogues respectively, which I believe has been a staple of the bear and cat form fantasies since 2004. Adding more feral-specific Wild Affinities may circumvent this issue somewhat, but I feel that without strong baseline abilities for each specialization, it will be difficult to capture that "Tank" or "Damage Dealer" feel as well. 

I suppose this is similar to choosing the vanilla design of druids, or the modern design. In Vanilla WoW, Druids were capable of filling out any role in the game, but not as well as classes dedicated to that role. This I think resembles the Full Caster option, where Druids would be able to feasibly deal melee damage or act as a damage sponge, but simply would(should) not be able to compete with the likes of Warriors and Rogues. In modern WoW, Druids can fill any role as capably as any other class. I feel that the Half Caster model resembles this. Restoration and Balance druids can cast as well as Mages and Priests with Full Casting, while the Ferals could fight with the effectiveness of dedicated martial classes with Half Casting.

Sorry for the essay, but I've been doing a lot of thinking on the subject, and want to help make the Druid (and the Handbook!) the best versions of themselves that they can be!
